### ISSUE TITLE
Non Blocking

### ISSUE THREAD

**Issue by nikhilkalige** [mohammed90/SIM900GSM#3] opened 2013-12-30 06:48 UTC
Hi, 

It is just my suggestion, we already have a lot of libraries for SIM900 with arduino, so going in the same direction would not be of any use. So if you suggest a way where in a non blocking code can be built, I would definitely like to contribute a lot to the same.. 

its just a suggestion....

**Comment by mohammed90** [comment] 2014-01-04 03:23
Hello,

I initially started this repo because I couldn't find any library for the SIM900 that is not bloated with other functionalities (like NFC and whatnot). However, your suggestion of non blocking code is good. The issue is that  I don't know any C++ nor do I have experience with creating non blocking code. I wrote the library in Arduino code and a generous GitHub user (carycode) converted it to an Arduino C++ library and merged it.

Please feel free to branch the repo, adjust it as you see fit, and merge it. I'll try to help in anyway I could.

Cheers.

**Closed as completed** 2014-01-29 05:55 UTC
